### ISSUE TITLE
Doesn't appear to install

### ISSUE THREAD

**Issue by MattHarvey89** [aaditmajmudar/completeworkflowhistory#1]
Hi,

We have installed the add on completeworkflowhistory on our community x5.0 edition of Alfresco however we do not see the add on after re-starting the system. It appears like the add on has not installed correctly/at all.

Please advise?

**Comment by aaditmajmudar** [comment]
Hi,

Thanks for downloading the addon.
This add on will give custom action per document/folder inside the document
library/repository in alfresco share.

Can you please elaborate more what is not working at your end?

Thanks,
Aadit Majmudar

**Comment by MattHarvey89** [comment]
Hi Aadit,

We have followed the installation instructions to install the add on to our Alfresco site, however we cannot see "show workflow history" as displayed on the gallery here (https://addons.alfresco.com/sites/addons/files/styles/very_large/public/addons_field_image/file__ajax/screen1.jpeg?itok=ylvtIxur) it looks as though the add on didn't install but we are confident we followed the instructions correctly.

Thanks,

Matt

**Comment by aaditmajmudar** [comment]
Hi Matt,

Is there any custom code you are having in your alfresco apart from this
addon?
If yes then any files from this addon conflicting with your custom code?

In share amp, config/alfresco/web-extension/share-config-custom.xml is
responsible to show the action "Show complate history".

Thanks,
Aadit

**Comment by MattHarvey89** [comment]
Hi Aadit,

Yes, our Alfresco site has bespoke code, however we have taken a look at the files from this add-on and do not believe they are conflicting. 

Apologies for the late response.

Thanks,

Matt

**Comment by aaditmajmudar** [comment]
Oh okay.!

Let me know if you want to do screen sharing so that I can look into that.
I have again checked with alfresco community 5.0 in my local and its
working fine.

Thanks,
Aadit

**Comment by MattHarvey89** [comment]
Brilliant, thank you. Could you let me know if you would need to see the UI, Linux or both?

Matt

**Comment by aaditmajmudar** [comment]
It would be great if I can see the UI, Linux and code base.

Thanks,
Aadit

**Comment by MattHarvey89** [comment]
Hi Aadit,

Okay, I do not have access to all of the above so I will arrange with someone who does to share with you. 

Unfortunately my normal go-to guy is on leave unit next Monday. 

I will send you some possible dates/times as soon as I can.

Thanks for your help up to now.

Matt

**Comment by aaditmajmudar** [comment]
Hi Matt,

Oh thats fine.
Anytime, lemme know when you want to have this session.

Thanks,
Aadit

**Comment by MattHarvey89** [comment]
Hi Aadit,

My contact in IT is back from leave today. I have spoken with him about the share we wish to do and he has asked the following questions we'll need to know before we can proceed, due to our network and security. 

You will need to use an SSH to connect to our machine. 
When would you like to connect and how long roughly would you like access for? Due to the fact we'll need someone monitoring your connection it will need to be between the hours of 09:00-16:30 BST.
What type of connection will you make to our machine?
Potentially we may need the IP address of the machine you will use to connect to us.

Thanks in advance,

Matt

**Comment by aaditmajmudar** [comment]
Hi Matt,

Sorry I was on vacation.
- Yes SSH connection to server is fine from my machine. (Assuming code base
- alfresco server on this server only as I need access of code also to
  check any conflict)
- I need around half an hour.
- Sure I can provide you the ip address.

We can setup go to meeting so that we can interact if any question during
that time.

Let me know the convenient time for this.

Thanks & Regards,
Aadit Majmudar

**Comment by MattHarvey89** [comment]
Hi Aadit, 

Apologies for the delay and short notice but would Monday be possible? (18th)

We would need to use TeamViewer if that's possible? 

Do you have any direct contact details I can provide to my IT contact to arrange time/ID tokens to connect?

Thanks,

Matt

**Comment by aaditmajmudar** [comment]
Hi Matt,

No problem.

Team viewer is fine.
Contact no: +91-9428354370

Let me know the timings between 10am IST to 10pm IST.

Thanks & Regards,
Aadit Majmudar

**Comment by MattHarvey89** [comment]
Hi Aadit,

Thanks for the reply. We have a priority fault we are dealing with currently so we may have to connect tomorrow depending on how we go. I'll let you know.

Thanks,

Matt

**Comment by MattHarvey89** [comment]
Hi Aadit,

Can we schedule 14:30 IST tomorrow to connect?

**Comment by MattHarvey89** [comment]
Hi Aadit,

Are you available now to dial in?

**Comment by aaditmajmudar** [comment]
Sorry Matt,

I just saw your mail.
Just let me know the timings a day before in advance so that I can dial
accordingly.

Thanks,
Aadit

**Comment by MattHarvey89** [comment]
Hi Aadit,

No problem, can we arrange for 14:30 IST tomorrow?

Thanks,

Matt

**Comment by MattHarvey89** [comment]
Aadit. 

Are you available to dial in?

**Comment by aaditmajmudar** [comment]
I am so sorry Matt, I just saw your mail as I used to work in VPN so could
not check the gmail.

Just call me on my cell to dial in anytime, +91-9428354370

Thanks,
Aadit Majmudar

**Comment by MattHarvey89** [comment]
Hi Aadit,

I will give you a call Monday to dial in.

**Comment by aaditmajmudar** [comment]
Hi Matt,

I am ready, dial in information?

Thanks,
Aadit

**Comment by MattHarvey89** [comment]
Hi Aadit,

Dial in information is as follows;

TeamViewer
ID: 719 906 633
Password: 3363

**Comment by aaditmajmudar** [comment]
Hi Matt,

I have just performed the same steps mentioned in readme file.

1) Stop the server
2) Apply the amps file
3) Restart the server

And the environment on which I have checked this issue was having tomcat
port number as 8083 instead of default 8080, so I have just allowed
alfresco share on 8083 port.

You can check this settings of port in
share-config-custom.xml(tomcat/webapps/share/WEB-INF/classes/alfresco/web-extension).

Let me know in case of any query.

Thanks & Regards,
Aadit Majmudar

**Comment by MattHarvey89** [comment]
Hi Aadit,

Thank you for your help this morning and thanks for the feedback.

I will let you know if we have any queries when applying the add on to our live system.

Thanks,

Matt

**Comment by aaditmajmudar** [comment]
Hi Matt,

Hope everything is fine with the addon.
Let me know in case of any query.

Can you please provide your comment on this addon?
It would be great if you can.
https://addons.alfresco.com/addons/complete-workflow-history

Thanks in advance.

Thanks,
Aadit Majmudar

**Comment by jonso18** [comment]
Hi Aadit,

this plugin is compatibility alfresco comunnity 5.1 ?

**Comment by aaditmajmudar** [comment]
Hi,

Yes its compatible with Alfresco 5.1
Let me know if you face any problem during installation of addon.

Thanks & Regards,
Aadit Majmudar
