### ISSUE TITLE
workflow Hoistory popup window - Actions icon broken

### ISSUE THREAD

**Issue by Paulo7414** [aaditmajmudar/completeworkflowhistory#3]
Hi,
Congratulations for the module, works like a charm.
The only exceptions are the icons under the Actions, the images src is broken, it has a extra trailing slash on the path:

<img id=yui-gen182" src="/share//res/components/images/task-16.png"

Using Alfresco Community 5.2

Best Regards,

Paulo Pereira

**Comment by aaditmajmudar** [comment]
Hi Paulo,

Great to hear positive words from you.
Thank you so much.

And Thank you for the exception pointer.
Will definitely change the source for that.

Keep posting the suggestions and improvements.

Thanks & Regards,
Aadit Majmudar

**Comment by aaditmajmudar** [comment]
Done.
Thanks.

**Comment by wessrafamessi** [comment]
@Paulo7414 hi , "I followed the package installation instructions, but I can't make use of it. How can I view the history of workflows?"
